title: 'America’s Public Bible: A Commentary'
params:
  author: 'Lincoln A. Mullen'
  description: 'How the Bible was used throughout American history.'

baseURL: 'https://dev.americaspublicbible.org/'

markup:
  goldmark:
    renderer:
      unsafe: true

disableKinds:
  - 'taxonomy'
  - 'taxonomyTerm'
