title: "America’s Public Bible: A Commentary"
params:
  author: "Lincoln A. Mullen"
  doiURL: "https://doi.org/10.21627/2022apb"
  doi: 10.21627/2022apb
  isbn: 978-1-5036-0524-4
  oclc: TBD
  oclcURL: "#"
  termsUrl: "#"
  year: 2022
  description: |
    Throughout the nineteenth century and into the twentieth century, newspapers in the United States—even newspapers which were not published by a religious denomination or organization—made frequent recourse to the Bible. Newspapers printed sermons and Sunday school lessons. They featured jokes whose punchlines required familiarity with the Bible and aired political commentary that cited the Bible on all sides of a given issue. 
    America's Public Bible is an interactive scholarly work that uncovers the history of the Bible in the nineteenth- and early twentieth-century United States. When the Bible was cited on one side or the other of an issue, only rarely was its meaning explicated rather than assumed. Those who cited the text most typically thought that their readers would understand its meaning precisely as they did. But the multiple and mutually exclusive ways in which newspapers used the Bible tests that assumption. By identifying and studying quotations in American newspapers, the site offers a commentary on how the Bible was used in public life, uncovering trends and patterns that would be invisible to a single scholar's reading of these documents.

baseURL: "https://dev.americaspublicbible.org/"

markup:
  goldmark:
    renderer:
      unsafe: true

disableKinds:
  - "taxonomy"
  - "taxonomyTerm"

build:
  noJSConfigInAssets: true
