title: 'America’s Public Bible: A Commentary'
params:
  author: 'Lincoln A. Mullen'
  description: 'How the Bible was used throughout American history.'

baseURL: 'https://dev.americaspublicbible.org/'
taxonomies:
  tag: ''
  category: ''

markup:
  goldmark:
    renderer:
      unsafe: true
